### ISSUE TITLE
Game freezes when click to sort item already inside chest to the same chest 

### ISSUE THREAD

**Issue by RLCarv** [AzumattDev/AzuAutoStore#5]
Hey, how you doing?

I noticed that using the latest biuld (though I'm quite sure I've encounter this behaviour on a previous one), if I have a chest open and I click on an item inside the chest with the button I use to autosort a single item (middle mouse button for me) the game freezes. 

I discovered this when moving items from one chest to another, where instead of using the left click to move the item from a chest to my inventory, I acidentaly pressed the middle button and it froze the game (I can still hear the game on the background but I have to quit it), .

I'm not familiar with how the code of this mod works but I imagine that if you check, when the "sort a single item" button is pressed, whether that item is inside a chest or not, and if true don't do nothing, that would solve the problem.

Have a good day!

**Comment by AzumattDev** [comment]
I forget when, but I'm pretty sure I fixed this awhile back.
